<?php
require 'auth.php';
$pageTitle = "إضافة مركز ومحطات";
require 'config.php';
$message = '';

if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $center_name = trim($_POST["center_name"]);
        $num_stations = (int) $_POST["num_stations"];
              
                  if ($center_name === "" || $num_stations <= 0) {
                          $message = "يرجى إدخال بيانات صحيحة.";
                              } else {
                                      try {
                                                  $stmt = $pdo->prepare("SELECT id FROM centers WHERE center_name = :center_name");
                                                              $stmt->execute(['center_name' => $center_name]);
                                                                          if ($stmt->rowCount() > 0) {
                                                                                          $message = "هذا المركز موجود بالفعل!";
                                                                                                      } else {
                                                                                                                      $stmt = $pdo->prepare("INSERT INTO centers (center_name) VALUES (:center_name)");
                                                                                                                                      $stmt->execute(['center_name' => $center_name]);
                                                                                                                                                      $center_id = $pdo->lastInsertId();
                                                                                                                                                                      $stmt2 = $pdo->prepare("INSERT INTO stations (center_id, station_number) VALUES (:center_id, :station_number)");
                                                                                                                                                                                      for ($i = 1; $i <= $num_stations; $i++) {
                                                                                                                                                                                                          $stmt2->execute([
                                                                                                                                                                                                                                  'center_id' => $center_id,
                                                                                                                                                                                                                                                          'station_number' => $i
                                                                                                                                                                                                                                                                              ]);
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                              $message = "تم إضافة المركز والمحطات بنجاح!";
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                  } catch (PDOException $e) {
                                                                                                                                                                                                                                                                                                                                              $message = "خطأ: " . $e->getMessage();
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                          include 'header.php';
                                                                                                                                                                                                                                                                                                                                                          ?>
                                                                                                                                                                                                                                                                                                                                                          <div class="card shadow-sm">
                                                                                                                                                                                                                                                                                                                                                            <div class="card-body">
                                                                                                                                                                                                                                                                                                                                                                <h2 class="card-title text-center mb-3">إضافة مركز ومحطات</h2>
                                                                                                                                                                                                                                                                                                                                                                    <?php if($message): ?>
                                                                                                                                                                                                                                                                                                                                                                          <div class="alert alert-info text-center"><?php echo $message; ?></div>
                                                                                                                                                                                                                                                                                                                                                                              <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                  <form method="POST">
                                                                                                                                                                                                                                                                                                                                                                                        <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                <label class="form-label">اسم المركز</label>
                                                                                                                                                                                                                                                                                                                                                                                                        <input type="text" name="center_name" class="form-control" placeholder="أدخل اسم المركز" required>
                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                            <label class="form-label">عدد المحطات</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="number" name="num_stations" class="form-control" placeholder="أدخل عدد المحطات" min="1" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="d-grid gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" class="btn btn-primary btn-custom">حفظ</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a href="index.php" class="btn btn-secondary btn-custom">عودة</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php include 'footer.php'; ?>