<?php
$pageTitle = "رفع ملف CSV للمراكز";
require 'config.php';

$message = '';

if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_FILES["csv_file"])) {
    $file = $_FILES["csv_file"]["tmp_name"];
          
              if ($file) {
                      if (($handle = fopen($file, "r")) !== FALSE) {
                                  // قراءة الصف الأول (العناوين) وتجاوزه
                                              $headers = fgetcsv($handle, 1000, ",");
                                                          while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
                                                                          if (count($data) < 2) continue;
                                                                                          $num_stations = trim($data[0]);
                                                                                                          $center_name = trim($data[1]);
                                                                                                                          if (!empty($center_name) && is_numeric($num_stations) && $num_stations > 0) {
                                                                                                                                              $stmt = $pdo->prepare("SELECT id FROM centers WHERE center_name = :center_name");
                                                                                                                                                                  $stmt->execute(['center_name' => $center_name]);
                                                                                                                                                                                      $center_id = $stmt->fetchColumn();
                                                                                                                                                                                                          if (!$center_id) {
                                                                                                                                                                                                                                  $stmt = $pdo->prepare("INSERT INTO centers (center_name) VALUES (:center_name)");
                                                                                                                                                                                                                                                          $stmt->execute(['center_name' => $center_name]);
                                                                                                                                                                                                                                                                                  $center_id = $pdo->lastInsertId();
                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                          for ($i = 1; $i <= $num_stations; $i++) {
                                                                                                                                                                                                                                                                                                                                                  $stmt = $pdo->prepare("SELECT COUNT(*) FROM stations WHERE center_id = :center_id AND station_number = :station_number");
                                                                                                                                                                                                                                                                                                                                                                          $stmt->execute(['center_id' => $center_id, 'station_number' => $i]);
                                                                                                                                                                                                                                                                                                                                                                                                  $exists = $stmt->fetchColumn();
                                                                                                                                                                                                                                                                                                                                                                                                                          if ($exists == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                      $stmt = $pdo->prepare("INSERT INTO stations (center_id, station_number) VALUES (:center_id, :station_number)");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $stmt->execute(['center_id' => $center_id, 'station_number' => $i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fclose($handle);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  $message = "✅ تم استيراد البيانات بنجاح!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      $message = "❌ فشل في فتح الملف.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          $message = "❌ يرجى اختيار ملف CSV.";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <!DOCTYPE html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <html lang="ar">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <meta charset="UTF-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <meta name="viewport" content="width=device-width, initial-scale=1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <title><?php echo $pageTitle; ?></title>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.rtl.min.css" rel="stylesheet">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        body { background-color: #f9fafb; direction: rtl; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              .container { max-width: 600px; margin-top: 30px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .btn-custom { border-radius: 50px; padding: 10px 20px; margin-top: 10px; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </style>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="container">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 class="text-center mb-4">رفع ملف CSV للمراكز والمحطات</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php if ($message): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="alert alert-info text-center"><?php echo $message; ?></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <form action="" method="post" enctype="multipart/form-data" class="border p-4 rounded shadow-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label class="form-label">اختر ملف CSV:</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input type="file" name="csv_file" class="form-control" accept=".csv" required>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button type="submit" class="btn btn-primary w-100 btn-custom">رفع واستيراد البيانات</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div class="text-center mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="index.php" class="btn btn-secondary btn-custom">عودة</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </html>